### ISSUE TITLE
your example run error 

### ISSUE THREAD

**Issue by aa4790139** [Subwaytime/vite-aliases#10]
![image](https://user-images.githubusercontent.com/9338717/111025592-0d2ffa00-8420-11eb-8225-9450af7ddedb.png)

**Comment by Subwaytime** [comment]
Ahh sorry for the late Answer, currently i am quite busy!

I will look into it :) And update it accordingly! 
thanks @aa4790139

**Comment by Subwaytime** [comment]
Should be fixed!
