### ISSUE TITLE
[eslint] A function with a name starting with an uppercase letter should only be used as a constructor. (new-cap)

### ISSUE THREAD

**Issue by tsanyqudsi** [Subwaytime/vite-aliases#22]
Hi there, it's me again.

Apparently your use of `ViteAliases()` has an issue with eslint.

the workaround is to use `import { ViteAliases as viteAliases } from 'vite-aliases'` but it's a bit annoying :) 

Also, when i use it, it needs to input the options, otherwise it would be :
```
Expected 1 arguments, but got 0.ts(2554)
index.d.ts(65, 30): An argument for 'options' was not provided.
```

**Comment by tsanyqudsi** [comment]
Ah for the error i think #20  already solved it.

**Comment by Subwaytime** [comment]
Hmm interesting Bug still.. ive taken the Idea for the Class Name from other Plugins, but if there is a workaround with the upcoming Patch then its good to know!
