### ISSUE TITLE
tsconfig without compilerOptions not supported

### ISSUE THREAD

**Issue by FunctionDJ** [Subwaytime/vite-aliases#26]
vite-aliases doesn't check if compileOptions exists in the tsconfig, and doesn't handle it.

So when using a tsconfig that uses `extend` to get it's compilerOptions and doesn't have it's own, a `TypeError` occurs: `Cannot read property 'paths' of undefined`

**Comment by FunctionDJ** [comment]
Kinda related to #25 since i tried `extend` to get around that issue and keep my comments in a `tsconfig.base.json` file.

**Comment by FunctionDJ** [comment]
Can be worked around by simply creating `"compilerOptions": { "paths": {} }`

**Comment by Subwaytime** [comment]
fixed with [v0.8.4](https://github.com/Subwaytime/vite-aliases/releases/tag/v0.8.4)
