### ISSUE TITLE
Chokidar file system watcher never stopped. 

### ISSUE THREAD

**Issue by Qocotzxin** [Subwaytime/vite-aliases#37]
While using [vitest](https://vitest.dev/)  to run my suite of tests I found an issue where, once the test run had finished, it couldn't properly shut down. After some research I found out the problem was this library. Another user took a look into this plugin source code and found that the chokidar fs watcher was never stopping which prevented vitest from closing.

Leaving the [related issue](https://github.com/vitest-dev/vitest/issues/1288)  here for background.

Thanks!

**Comment by Subwaytime** [comment]
Hey there! Thanks for the Report, ill look into it. 
`chokidar` is hooked into the dev-servermode of `vite`, so there might be changes to `vitest`that arent the same as in `vite`.
