### ISSUE TITLE
bug: vite aliases override all config.resolve.alias

### ISSUE THREAD

**Issue by lior-a** [Subwaytime/vite-aliases#38]
https://github.com/Subwaytime/vite-aliases/blob/main/src/index.ts#L16
it override previously, manually inserted aliases.

if you want i can submit a PR

**Comment by Subwaytime** [comment]
quick fixed in this commit https://github.com/Subwaytime/vite-aliases/commit/1b28124c0ee6da941630dbfdd308552ff6eb6717, will be in the next release!
