### ISSUE TITLE
Don't forget about baseURL

### ISSUE THREAD

**Issue by seivan** [Subwaytime/vite-aliases#39]
In my case, I don't use path aliases.
I just use `"baseUrl": "src",`

So I can import from root. 

Then all I needed was 
```ts
  resolve: {
    alias: resolveBaseURL() // {"src":  srcDir}
  },
  ```

So I thought I could just replace that line with the plugin.
And have TSConfig be the source of truth. 

But I think, you had a different idea? You would write to the TSConfig or make an in-memory version of it? 

Can I suggest an alternative approach? 

Make them mutually exclusive. 
The arguments either take (almost) all the `Omit<Options, 'tsconfig'>` it currently take, or `tsconfigPath`.

From TSConfig, you don't need to recursively loop through directories or all that jazz, the definitions are already made for you, things like `baseURL` and `aliases` are defined by the user. 

This [guy](https://github.com/davestewart/alias-hq#overview) got the right idea.

**Comment by Subwaytime** [comment]
The Idea of vite-aliases is to generate aliases based on your folder structure and create a js/ts config along side it, so you dont have define it at all. 

Technically speaking, its pretty easy to extend with an existing tsconfig, but that kinda defeats the purpose of this package.

If i understand your proposal right..

**Comment by seivan** [comment]
This definition is it just in memory or one the file system? The problem would be that the type checker would complain if you don’t have it on tsconfig as well. 

But if you need it there as well the file system then my guess is it would cause issues if they mismatch, am I wrong?

**Comment by seivan** [comment]
Oh ok. Thanks for clarifying that.
