### ISSUE TITLE
Add automatic Path Generation for tsconfig/jsconfig

### ISSUE THREAD

**Issue by Subwaytime** [Subwaytime/vite-aliases#4]
This Feature is basically there just to fix issues with VSCode.
Atm its adviced to have a `paths` Array in TSConfig or JSConfig.

**Comment by tsanyqudsi** [comment]
@Subwaytime a suggestion just for the "as long it's work" workaround.

Maybe we could manipulate the array generated by `vite-aliases` using regex and append it to tsconfig/jsconfig ?

I'm not a good programmer but i can try to find out how. This is an epic plugin !!

**Comment by tsanyqudsi** [comment]
@Subwaytime i made a PR for this issue in #16
