### ISSUE TITLE
Vite 3 support - supported starting v0.9.5!

### ISSUE THREAD

**Issue by Subwaytime** [Subwaytime/vite-aliases#40]
- add vite 3 support
- add vitest (latest) support
- fix issues [[33](https://github.com/Subwaytime/vite-aliases/issues/33), [37](https://github.com/Subwaytime/vite-aliases/issues/37), [38](https://github.com/Subwaytime/vite-aliases/issues/38)]

**Comment by Subwaytime** [comment]
quick note, its still beeing worked on! I am currently quite busy to tackle this, vite 3 technically works, but it just doesnt have full esm support! (using type module in package.json)

**Comment by Subwaytime** [comment]
Part of this PR: https://github.com/Subwaytime/vite-aliases/pull/41
There will be upcoming other changes before a new release is triggered

**Comment by tobychidiu** [comment]
Will this fix the Typescript issues?

**Comment by Subwaytime** [comment]
Yes, there is already a pre-release, but i am doing some major rewrites, as the comment json package is causing the esm/cjs issue.

**Comment by Subwaytime** [comment]
Check the [v10](https://github.com/Subwaytime/vite-aliases/tree/v10) - Development Branch! Prerelease v0.9.5 ensures Vite 3 support and should fix the Bugs above, please report any Bugs that are found! As some parts have changed drastically to fully support esm

**Comment by nichita-pasecinic** [comment]
@Subwaytime How to install the pre-release version ?

**Comment by Subwaytime** [comment]
There will be an official release for v10 tomorrow!

**Comment by nichita-pasecinic** [comment]
Thanks!
