### ISSUE TITLE
New version seems to break Vite 2

### ISSUE THREAD

**Issue by edankwan** [Subwaytime/vite-aliases#45]
I got the `No "exports" main defined in /opt/build/repo/node_modules/vite-aliases/package.json` error.

**Comment by Subwaytime** [comment]
You have to add `type: "module"` to your package.json, as this package moved over to ESM. Also vite 2 support is not guaranteed anymore with newer versions of this package, as vite 3 and the upcoming vite 4 have major breaking changes to the plugin structure, it is also not advised to keep using it! ;)
