### ISSUE TITLE
Solid JS error

### ISSUE THREAD

**Issue by tsanyqudsi** [Subwaytime/vite-aliases#46]
The main issue with SolidJS in vite using `vite-aliases` are :

- Aliases are not generating in `config.resolve.alias`

```
Generator {
  options: {
    dir: 'src',
    prefix: '@',
    deep: true,
    depth: 1,
    createGlobalAlias: true,
    createLog: false,
    logPath: 'src/logs',
    adjustDuplicates: false,
    useAbsolute: false,
    useConfig: true,
    useIndexes: true,
    useTypescript: true,
    root: '***Omitted***'
  },
  fullPath: '***Omitted***',
  aliases: [],
  directories: Set(0) {},
  paths: {},
  searched: false,
  servermode: 'serve'
}
```
- `ERR_PACKAGE_PATH_NOT_EXPORTED`  ( current workaround is to update the package.json ).
```
Couldn't find package.json for vite-aliases Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: No "exports" main defined in ***Omitted***\node_modules\vite-aliases\package.json
    at new NodeError (node:internal/errors:387:5)
    at throwExportsNotFound (node:internal/modules/esm/resolve:365:9)
    at packageExportsResolve (node:internal/modules/esm/resolve:589:7)
    at resolveExports (node:internal/modules/cjs/loader:522:36)
    at Function.Module._findPath (node:internal/modules/cjs/loader:562:31)
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:971:27)
    at Function.resolve (node:internal/modules/cjs/helpers:109:19)
    at***Omitted***node_modules/vite-plugin-solid/dist/esm/index.mjs:53:35
    at Array.map (<anonymous>)
    at getSolidDeps (***Omitted***node_modules/vite-plugin-solid/dist/esm/index.mjs:48:21) {
  code: 'ERR_PACKAGE_PATH_NOT_EXPORTED'
}
```

Your example is working well so I figures it's because of another vite plugins. I haven't check with react but I will later.

I'm using Windows 10 btw, haven't test it on Linux.

_Originally posted by @tsanyqudsi in https://github.com/Subwaytime/vite-aliases/issues/43#issuecomment-1283410165_

**Comment by Subwaytime** [comment]
I havent had the time to setup SolidJs but might be able todo it this Weekend and see if i can find the error. I think it might still have something todo with the esm move, so ill investigate!

**Comment by Subwaytime** [comment]
Hm, so i cant seem to reproduce this! vite-aliases package.json has a exports section that should definitely be picked up..
could you provide a test repo? :thinking: - Otherwise i am not sure if i can find the issue on my system..

**Comment by tsanyqudsi** [comment]
@Subwaytime 

I've set up the repo on https://github.com/tsanyqudsi/vite-aliases-monorepo-test. But most probably it's because of Monorepo setting.

However, you can compare it with the react version ( i've set up in the same monorepo ).

**Comment by houd1ni** [comment]
node -v  v19.1.0
"vite": "^3.2.4",
"vite-aliases": "^0.9.7",

![image](https://user-images.githubusercontent.com/7501201/202346736-5600c896-afdf-4068-b946-a7f6a97eae08.png)

**Comment by tsanyqudsi** [comment]
@houd1ni https://github.com/Subwaytime/vite-aliases/issues/43#issuecomment-1285106211

**Comment by Subwaytime** [comment]
Working on some fixes atm! This seems to also clear the solidjs issue.. :100:

**Comment by houd1ni** [comment]
> @houd1ni [#43 (comment)](https://github.com/Subwaytime/vite-aliases/issues/43#issuecomment-1285106211)
> 
> The same question was asked and answered there. please do mind to check the issues using the search field.

Is "I can't reproduce" an answer, really ?
Or "most probably due to monorepo" is an answer ?
I have no monorepo setting. And due to this half-abandoned issue, forced to use other solutions.

**Comment by tsanyqudsi** [comment]
> > @houd1ni [#43 (comment)](https://github.com/Subwaytime/vite-aliases/issues/43#issuecomment-1285106211)
> > The same question was asked and answered there. please do mind to check the issues using the search field.
> 
> Is "I can't reproduce" an answer, really ? Or "most probably due to monorepo" is an answer ? I have no monorepo setting. And due to this half-abandoned issue, forced to use other solutions.

If you actually CLICKED the link provided, you should see this kind of view :

![Untitled](https://user-images.githubusercontent.com/1050880/205185199-e134b129-1df6-4c08-8ab9-34df9bd1e6e6.png)

And that's the answer.

Mind that you displayed a despicable attitude in an open source project towards someone who IS NOT the owner of the project that trying to help.

Also barging in with your own Issue unrelated with the title of the issue and acting entitled.

**Comment by houd1ni** [comment]
> > > @houd1ni [#43 (comment)](https://github.com/Subwaytime/vite-aliases/issues/43#issuecomment-1285106211)
> > > The same question was asked and answered there. please do mind to check the issues using the search field.
> > 
> > 
> > Is "I can't reproduce" an answer, really ? Or "most probably due to monorepo" is an answer ? I have no monorepo setting. And due to this half-abandoned issue, forced to use other solutions.
> 
> If you actually CLICKED the link provided, you should see this kind of view :
> 
> ![Untitled](https://user-images.githubusercontent.com/1050880/205185199-e134b129-1df6-4c08-8ab9-34df9bd1e6e6.png)
> 
> And that's the answer.
> 
> Mind that you displayed a despicable attitude in an open source project towards someone who IS NOT the owner of the project that trying to help.
> 
> Also barging in with your own Issue unrelated with the title of the issue and acting entitled.

Why wouldn't you just close this issue with the provided solution to not to misguide some people ?
I was really sure that if there's a similar issue, they must be connected or, even better, merged into one.

**Comment by tsanyqudsi** [comment]
@houd1ni Because it's a different Issue, If you actually learn github or ACTUALLY able to read. then you should see :

![image](https://user-images.githubusercontent.com/1050880/205438483-3c94b94d-8d92-4173-88e8-3146c21ea39c.png)

Plus if you actually able to differentiate words. then you should see :

![image](https://user-images.githubusercontent.com/1050880/205438510-931fd6e8-d232-4312-9ded-515086e4b8d9.png)

It's an issue FROM #43 that I CREATED. But since it grows into another issue so I actually split it and it becomes #46. 

This is an issue for SolidJS and if you read my comment :

![image](https://user-images.githubusercontent.com/1050880/205438636-031ad977-757a-4b84-888e-380eaf601f20.png)

I actually wrote "ERR_PACKAGE_PATH_NOT_EXPORTED ( current workaround is to update the package.json )." which IF you checked the post origin which was #43 it should showed that the solution was there.

Yes, it's connected. 
Yes, I'm using Github's feature to split issues.

Only those who can't read complains and felt misguided.

**Comment by Subwaytime** [comment]
It seems both issues are not related, so i am trying to fix all three, including the newly posted one.

**Comment by Subwaytime** [comment]
@tsanyqudsi hey there, sorry for the late response! i have just put out v0.10.0 - this seems to have fixed the issue, atleast for me, can you confirm on our end if it works?

**Comment by Subwaytime** [comment]
@houd1ni your issue should be fixed now with latest version v0.10.0!

**Comment by houd1ni** [comment]
> @houd1ni [#43 (comment)](https://github.com/Subwaytime/vite-aliases/issues/43#issuecomment-1285106211)
> 
> The same question was asked and answered there. please do mind to check the issues using the search field.

Hi! Tried it to ensure that issue is fixed. With the initial setup

```
ViteAliases({
      useTypescript: true,
      // root: './project-front'
    })
```

it generates output below. With root option uncommented, `ERROR  [vite-aliases]` disappears, but next lines are the same. `deep: true` doesn't have any impact on this. By the way, the package.json is in one level higher directory that the vite.config.mts, and the command, as you can see in the output, is executed in that upper dir. `resolve` vite option and other plugins that might affect this, I have disabled also.

```
  ERROR  [vite-aliases] - No Directories could be found!                                                                                    10:28:36  

  at getDirectories (/H:/p/project-front/node_modules/vite-aliases/dist/index.js:132:18)
  at async Generator.init (/H:/p/project-front/node_modules/vite-aliases/dist/index.js:238:5)


  VITE v4.0.4  ready in 617 ms

  ➜  Local:   http://localhost:5173/
  ➜  Network: http://192.168.0.100:5173/
  ➜  press h to show help
X [ERROR] [plugin vite:dep-scan] Cannot read properties of undefined (reading 'length')

    node_modules/esbuild/lib/main.js:1357:21:
      1357 │         let result = await callback({
           ╵                      ^

    at matches$1 (file:///H:/p/project-front/node_modules/vite/dist/node/chunks/dep-5e7f419b.js:152:35)
    at file:///H:/p/project-front/node_modules/vite/dist/node/chunks/dep-5e7f419b.js:215:58
    at Array.find (<anonymous>)
    at Context.resolveId (file:///H:/p/project-front/node_modules/vite/dist/node/chunks/dep-5e7f419b.js:215:42)
    at Object.resolveId (file:///H:/p/project-front/node_modules/vite/dist/node/chunks/dep-5e7f419b.js:41433:46)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async resolve (file:///H:/p/project-front/node_modules/vite/dist/node/chunks/dep-5e7f419b.js:41661:26)
    at async file:///H:/p/project-front/node_modules/vite/dist/node/chunks/dep-5e7f419b.js:41718:34
    at async requestCallbacks.on-resolve (H:\p\project-front\node_modules\esbuild\lib\main.js:1357:22)
    at async handleRequest (H:\p\project-front\node_modules\esbuild\lib\main.js:723:13)

  This error came from the "onResolve" callback registered here:

    node_modules/esbuild/lib/main.js:1281:20:
      1281 │       let promise = setup({
```

**Comment by ChenChenyaqi** [comment]
import { ViteAliases } from "./node_modules/vite-aliases"

**Comment by Subwaytime** [comment]
@houd1ni - have you tried setting the directory? 
```js
ViteAliases({
    dir: './project-front'
});

**Comment by Subwaytime** [comment]
Any more Information on these Bugs would be great, as i cannot replicate them. Due to the Issues beeing stale, i have now closed them till there is more Information for me available that i can work with.
