### ISSUE TITLE
Plugin is forcing 4 spaces indentation when writing tsconfig

### ISSUE THREAD

**Issue by AmrAbdulrahman** [Subwaytime/vite-aliases#55]
Plugin is forcing 4 spaces indentation when writing tsconfig.

What I suggest is to fix this is

1. either interpret the current indentation from tsconfig
2. or add an option for formatting `{ indentation: 'tabs' | number }`

I am happy to open a MR if we agree on this.

**Comment by AmrAbdulrahman** [comment]
Link to MR: https://github.com/Subwaytime/vite-aliases/pull/56

**Comment by Subwaytime** [comment]
Hey there! This is an amazing idea, didnt think about! 👍 

Will checkout your PR tomorrow as i have got some time for open source work then !

**Comment by Subwaytime** [comment]
merged in with #56

**Comment by AmrAbdulrahman** [comment]
@Subwaytime let's please release 0.11.0 🙏
