### ISSUE TITLE
Ts error message

### ISSUE THREAD

**Issue by chengwi** [Subwaytime/vite-aliases#58]
![image](https://user-images.githubusercontent.com/18453753/225866469-08166e9d-0e8b-4a48-8ddf-2d5e1f2036ee.png)
I have configured this plugin in my TS project and it shows this TS error message, but it doesn't affect the normal functionality.

**Comment by Subwaytime** [comment]
Hm interesting, ill have a look! Seems to be that Vite has changed their typing again for Plugins :thinking:

**Comment by Subwaytime** [comment]
Should be fixed finally in [v0.11.1](https://github.com/Subwaytime/vite-aliases/releases/tag/v0.11.1)
