### ISSUE TITLE
Creating wrong TSConfig paths

### ISSUE THREAD

**Issue by tnfssc** [Subwaytime/vite-aliases#62]
I have my ViteJS project located in a folder `~/myprojects/web/src/foobar-project-007`. When I run `vite`, it produced wrong tsconfig paths. I got `src/foobar-project-007/src/components/*`, `src/foobar-project-007/src/lib/*`, `src/foobar-project-007/src/utils/*` etc.

Maybe the problem is with having the project in a folder with name `src`. But I really have no idea

**Comment by Subwaytime** [comment]
Could you share your config? As well as turning on the log and posting it here!

**Comment by Subwaytime** [comment]
stale
