### ISSUE TITLE
0.11.2 version cannot merge aliases in vite.config.ts

### ISSUE THREAD

**Issue by jojo-tan** [Subwaytime/vite-aliases#65]
After setting the alias in vite.config.ts, the gen.aliases in vite aliases src index.ts were deconstructed and lost their reference relationship, resulting in vite aliases not taking effect. Version 0.11.2

**Comment by Subwaytime** [comment]
Hey there, you could give me a bit more info what you are using and how your `vite.config.ts` looks like?

Can't replicate the Issue you mentioned!
