### ISSUE TITLE
Aliases not working 

### ISSUE THREAD

**Issue by issam-seghir** [Subwaytime/vite-aliases#69]
![image](https://github.com/Subwaytime/vite-aliases/assets/74573675/b13aef78-9c41-4b20-95f0-76d6102102c8)

this is the config generated by the plugin but is not working, when i use these aliases 

![image](https://github.com/Subwaytime/vite-aliases/assets/74573675/c837c73c-3993-4d0c-b3b4-5b00592efd67)

![image](https://github.com/Subwaytime/vite-aliases/assets/74573675/918b5384-9593-422a-b3ac-b76156b8e058)

this is my vite config :
```js
import AutoImport from "unplugin-auto-import/vite";
// import Icons from "unplugin-icons/vite";
import { defineConfig } from "vite";
import { ViteAliases } from "vite-aliases";
import dynamicImport from "vite-plugin-dynamic-import";

export default defineConfig(({ command, mode, ssrBuild }) => ({
	plugins: [
		dynamicImport(/* options */),
		AutoImport({
			/* options */
		}),
		ViteAliases(),
	],
}));
```

**Comment by Subwaytime** [comment]
Hm, it works fine for me.. 
It might be vite thats trying to handle the static assets differently, have you checked what happens if you import the file directly?

**Comment by issam-seghir** [comment]
I can confirm that the alias works in CSS, but not in HTML
could you explain what you mean by importing directly and provide an example?

this is my config : 
```js
plugins: [
		ViteAliases({
			dir: "src",
			prefix: "@",
			deep: true,
			depth: 1,
			/**
			 * Disables any terminal output
			 */
			silent: false,
		}),
	],
```

**Comment by Subwaytime** [comment]
It seems that vite's static asset loading is interfering here.
Importing directly like:

`import img from '@assets/logo/logo.svg'`

https://vitejs.dev/guide/assets.html#importing-asset-as-url

Note: It could be a bug in vite, as css url is handled the same way as img-tags.

**Comment by issam-seghir** [comment]
I understand your point, but I am using vanilla JavaScript in my project without any framework. I am not sure where to import the assets from ?
and It's possible that if I import all of my assets, the advantages of this plugin could be lost, although using aliases for shortcuts could save time, importing all of my assets would be a waste of time.

**Comment by issam-seghir** [comment]
do you know how to activate IDE autocomplete for aliases? When I type `import "@..."`, the path autocomplete doesn't work.

**Comment by issam-seghir** [comment]
I found out how to do it. I activated this  in the settings.
![image](https://github.com/Subwaytime/vite-aliases/assets/74573675/4255fb02-d683-4678-81ad-3a5084f1c3a5)

**Comment by Subwaytime** [comment]
Looks like this is based of rollup and vite. Nothing i can do here for the moment!
