### ISSUE TITLE
Change Vite Dependency to Peer Dependency

### ISSUE THREAD

**Issue by ColinKrist** [Subwaytime/vite-aliases#71]
The package.json strictly calls out v4 - v5 just got released and I am currently able to run this on my V5 project, but its also pulling in vite v4 alongside v5 which probably doesn't need to happen.

I believe peer dependencies should be used in this case to support multiple major versions

**Comment by Subwaytime** [comment]
Hey there, thanks for the Issue!
I am currently working on a newer version which fixes this problem!
Probably gonna drop next week..

**Comment by Subwaytime** [comment]
Considering i got a lot of messages regarding Vite 5, i just want to state that this Package fully works with Vite 5 - there are no issues with it.

**Comment by ColinKrist** [comment]
![image](https://github.com/Subwaytime/vite-aliases/assets/27971797/2e070a64-fd26-406f-a697-69c4ae9d1a86)

I haven't checked this package in a bit, but vite is still a direct dependency pictured above. That means when Vite has another major version release (v6) everyone is hung out to dry without installing both versions of vite into their node_modules.

I am suggesting a transition to using vite as a peerDependency to enable the usage of version ranges. There's a few pros to this model -

1. It only installs the user's desired version of vite and not what's specified in this project's `dependencies`. Fixes issue I've mentioned above
2. It only allows supported versions of vite to be installed in the user's project. (Not allowing users to use without officially supporting by adding to the dependency range)
3. A small PR just needs to be opened to add the range and update the example project to validate the plugin still works with the new version of vite.
4. Allows for multiple versions 

```
 "peerDependencies": {
    "dependency-name": "^1.0.0 || ^2.0.0"
  }
```

**Comment by ColinKrist** [comment]
Feel free to close this when `0.12` is published - I had some time before lunch to review and see it's now listed as a `devDependency` for the `Plugin` type which should resolve the issue that's happening now.

I hadn't dug into the code to check if you were using a utility function from vite, but happy the problem is resolving itself naturally without major changes.

**Comment by Subwaytime** [comment]
Hey there!
Yes that is the current plan, right now there is still some parts used for vite, but these are removed to only types in the next Version `0.12`.

Definitely moving vite towards peer :)

**Comment by Subwaytime** [comment]
Moved this towards peer now as `0.12` will still take some more time!
